### ISSUE TITLE
ActionLipStatusProvider throws errors where implemented

### ISSUE THREAD

**Issue by NightmindOfficial** [VICFR1TZ/linum#18]
════════ Exception caught by foundation library ════════════════════════════════
The following assertion was thrown while dispatching notifications for ActionLipStatusProvider:
setState() or markNeedsBuild() called during build.

This _InheritedProviderScope<ActionLipStatusProvider> widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: _InheritedProviderScope<ActionLipStatusProvider>
    value: Instance of 'ActionLipStatusProvider'
    listening to value
The widget which was currently being built when the offending call was made was: ScreenSkeleton
    dirty
    dependencies: [_InheritedProviderScope<BalanceDataProvider>]
When the exception was thrown, this was the stack
#0      Element.markNeedsBuild.<anonymous closure>
#1      Element.markNeedsBuild
#2      _InheritedProviderScopeElement.markNeedsNotifyDependents
#3      ChangeNotifier.notifyListeners
#4      ActionLipStatusProvider.setActionLipStatus
#5      ScreenSkeleton.build
#6      StatelessElement.build
#7      ComponentElement.performRebuild
#8      Element.rebuild
#9      ComponentElement._firstBuild
#10     ComponentElement.mount
...     Normal element mounting (9 frames)
#19     Element.inflateWidget
#20     Element.updateChild
#21     ComponentElement.performRebuild
#22     StatefulElement.performRebuild
#23     Element.rebuild
#24     StatefulElement.update
#25     Element.updateChild
#26     SingleChildRenderObjectElement.update
#27     Element.updateChild
#28     ComponentElement.performRebuild
#29     Element.rebuild
#30     StatelessElement.update
#31     Element.updateChild
#32     ComponentElement.performRebuild
#33     Element.rebuild
#34     ProxyElement.update
#35     Element.updateChild
#36     ComponentElement.performRebuild
#37     Element.rebuild
#38     ProxyElement.update
#39     Element.updateChild
#40     RenderObjectElement.updateChildren
#41     MultiChildRenderObjectElement.update
#42     Element.updateChild
#43     ComponentElement.performRebuild
#44     StatefulElement.performRebuild
#45     Element.rebuild
#46     StatefulElement.update
#47     Element.updateChild
#48     ComponentElement.performRebuild
#49     Element.rebuild
#50     ProxyElement.update
#51     Element.updateChild
#52     ComponentElement.performRebuild
#53     StatefulElement.performRebuild
#54     Element.rebuild
#55     StatefulElement.update
#56     Element.updateChild
#57     SingleChildRenderObjectElement.update
#58     Element.updateChild
#59     ComponentElement.performRebuild
#60     Element.rebuild
#61     StatelessElement.update
#62     Element.updateChild
#63     SingleChildRenderObjectElement.update
#64     Element.updateChild
#65     ComponentElement.performRebuild
#66     StatefulElement.performRebuild
#67     Element.rebuild
#68     StatefulElement.update
#69     Element.updateChild
#70     ComponentElement.performRebuild
#71     StatefulElement.performRebuild
#72     Element.rebuild
#73     StatefulElement.update
#74     Element.updateChild
#75     ComponentElement.performRebuild
#76     Element.rebuild
#77     ProxyElement.update
#78     Element.updateChild
#79     ComponentElement.performRebuild
#80     Element.rebuild
#81     StatelessElement.update
#82     Element.updateChild
#83     ComponentElement.performRebuild
#84     StatefulElement.performRebuild
#85     Element.rebuild
#86     StatefulElement.update
#87     Element.updateChild
#88     ComponentElement.performRebuild
#89     Element.rebuild
#90     ProxyElement.update
#91     Element.updateChild
#92     ComponentElement.performRebuild
#93     StatefulElement.performRebuild
#94     Element.rebuild
#95     StatefulElement.update
#96     Element.updateChild
#97     ComponentElement.performRebuild
#98     StatefulElement.performRebuild
#99     Element.rebuild
#100    BuildOwner.buildScope
#101    WidgetsBinding.drawFrame
#102    RendererBinding._handlePersistentFrameCallback
#103    SchedulerBinding._invokeFrameCallback
#104    SchedulerBinding.handleDrawFrame
#105    SchedulerBinding._handleDrawFrame
#109    _invoke (dart:ui/hooks.dart:150:10)
#110    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#111    _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)
The ActionLipStatusProvider sending notification was: Instance of 'ActionLipStatusProvider'
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by foundation library ════════════════════════════════
setState() or markNeedsBuild() called during build.
════════════════════════════════════════════════════════════════════════════════

**Comment by NightmindOfficial** [comment]
@SoTBurst dicke Kudos!

We don't know what solved the issue, nor do we exactly know what caused the error specifically.
The only important thing is that It works now.

Don't touch a thing that already works...
